name: bygg-frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v4

      - name: Sett opp Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Installer avhengigheter (legacy peer deps)
        env:
          npm_config_legacy_peer_deps: true
        run: npm ci --no-audit --no-fund

      - name: Bygg for produksjon
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
        run: npm run build -- --mode production

      - name: Verifiser at API-URL er bakt inn
        run: grep -R "${{ secrets.VITE_API_BASE_URL }}" dist -n

      - name: Last opp artefakt
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Last ned bygget
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Sjekk at secrets finnes
        run: |
          test -n "${{ secrets.SSH_PRIVATE_KEY }}" || (echo "SSH_PRIVATE_KEY mangler"; exit 1)
          test -n "${{ vars.DEPLOY_HOST }}"     || (echo "DEPLOY_HOST mangler"; exit 1)
          test -n "${{ vars.DEPLOY_USER }}"     || (echo "DEPLOY_USER mangler"; exit 1)
          test -n "${{ vars.DEPLOY_PATH }}"     || (echo "DEPLOY_PATH mangler"; exit 1)

      - name: Start ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          log-public-key: true

      - name: Legg til known_hosts
        run: ssh-keyscan -H ${{ vars.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Opprett målmappe (om mangler)
        run: ssh ${{ vars.DEPLOY_USER }}@${{ vars.DEPLOY_HOST }} 'mkdir -p ${{ vars.DEPLOY_PATH }}'

      - name: Rsync til webkatalog
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=yes" \
            dist/ "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/"

      - name: Reload Apache (valgfritt)
        run: ssh ${{ vars.DEPLOY_USER }}@${{ vars.DEPLOY_HOST }} 'sudo systemctl reload apache2 || true'
