name: Bygg og deploy personlighetstest-frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Sjekk ut repo
        uses: actions/checkout@v4

      - name: Sett opp Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Installer avhengigheter (legacy peer deps)
        run: npm install --legacy-peer-deps

      - name: Bygg
        run: npm run build

      - name: Installer SSH-nøkkel for deploy
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Kopier bygget til server
        run: |
          rsync -avz --delete \
            dist/ \
            vds@mysql.grendel.no:/path/til/www/personlighetstest/personlighetstest-frontend/dist/