name: bygg-frontend-dev

on:
  push:
    branches: [ dev ] # Bare kjør når dev oppdateres
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v4

      - name: Sett opp Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Installer avhengigheter (legacy peer deps)
        env:
          npm_config_legacy_peer_deps: true
        run: npm ci --no-audit --no-fund

      - name: Bygg for dev
        env:
          VITE_API_BASE_URL: http://localhost:5000/api
        run: npm run build -- --mode development

      - name: Last opp artefakt (for å sjekke i GitHub UI)
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist